### ISSUE TITLE
Add hhh's Crocus theme?

### ISSUE THREAD

**Issue by ghost** [BunsenLabs/bunsen-themes#14]
Exhibit at https://forums.bunsenlabs.org/viewtopic.php?pid=23716#p23716.

**Comment by capn-damo** [comment]
In bunsen-extras, or one of the default choices? Looks lovely in the scrots, but I found it hard to use in practise.

BTW Things like this is what I envisaged the BL deviantart group for - a source and showcase for artwork, themes etc.

**Comment by hhhorb** [comment]
> I found it hard to use in practise.

Because of it's dependency on transparency to identify the active window, or something else? Setting a different active title-bar color in the OB theme will fix the former.

This ties in with my "Visual Refresh" forum thread, which I'm still thinking about. Let's put this issue on hold for a few days, please.

https://forums.bunsenlabs.org/viewtopic.php?id=1713
