### ISSUE TITLE
gtk @import errors

### ISSUE THREAD

**Issue by capn-damo** [BunsenLabs/bunsen-themes#3]
gtk.css has the line `@import url("apps/lightdm-gtk-greeter.css")` which is throwing up a terminal error:
`Gtk-WARNING **: Theme parsing error: gtk.css:74:44: Failed to import: Error opening file: No such file or directory`

There is no `gtk-3.0/apps/lightdm-gtk-greeter.css` in the themes, except for `Bunsen-lightdm`

Commenting out the `@import` line stops the error

**Comment by ghost** [comment]
Hm, but every theme includes a lightdm-unity-greeter.css file. I'm unsure as to whether @hhhorb is still planning to add gtk greeter styling, but since re-adding these @import lines later is no problem, I am going to patch the unused @imports out for now.

**Comment by hhhorb** [comment]
I managed to miss this issue, so sorry. To explain, I split the default lightdm theme out of the GTK theme because I wanted the greeter panel to use symbolic icons and the line I used to remove most of the symbolic icons from the gtk3 file chooser was overriding the lightdm css. Removing the gtk.css @import lines was the right thing to do.
